/*로그 저장용 시퀀스*/
CREATE SEQUENCE log_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
CACHE 100;

DROP TABLE user_log PURGE;
/*임시 로그 테이블*/
CREATE TABLE user_log(
LOG_ID NUMBER PRIMARY KEY,
MEM_ID VARCHAR2(50),
CATE_ID VARCHAR2(20),
NEWS_ID VARCHAR2(50),
VIEW_TIME TIMESTAMP DEFAULT(LOCALTIMESTAMP)
);

/*임시 카테고리 선택 테이블*/
CREATE TABLE test_pref(
CATE_ID VARCHAR2(20),
MEM_ID VARCHAR2(50),
STATUS NUMBER(2) DEFAULT(0)
);

/*임시 뉴스 테이블*/
CREATE TABLE test_news(
NEWS_ID VARCHAR2(50),
CATE_ID VARCHAR2(20),
TITLE VARCHAR2(1000),
CONTENT VARCHAR2(1000),
VIEWS NUMBER,
LINK VARCHAR2(1000)
);