server.port=8090

spring.datasource.url=jdbc:oracle:thin:@13.209.75.71:1521:xe?oracle.jdbc.timezoneAsRegion=false&sessionTimeZone=Asia/Seoul
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
#spring.jpa.show-sql=true
#spring.

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=snews
spring.datasource.password=snews

#encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#email
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = shortnews110@gmail.com
spring.mail.password = dqpr vpqu vztm wfsg
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

#kakao
kakao.client.id = 8a2ff1aebc8f8febeb2c9a8a578f5c14
kakao.redirect.uri = http://www.shortnews.kr/login/oauth2/code/kakao
#kakao.redirect.uri = http://localhost:8090/login/oauth2/code/kakao
kakao.client.secret =

#naver
naver.client.id = sj_6_nYmN3OOAG4Ahwpi
naver.client.secret = 8dFrWorq5l
naver.redirect.uri = http://www.shortnews.kr/login/oauth2/code/naver
naver.auth.uri = https://nid.naver.com
naver.api.uri = https://openapi.naver.com

#google(ShortNews?)
google.client.id = 667842968610-jv8v8gqtf3infk3egpokf2ps0cthu99e.apps.googleusercontent.com
google.client.pw = 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
google.redirect.uri = https://www.shortnews.kr/login/oauth2/code/google

#SMS
sms.api.key = NCSGFHP5US4RJU99
sms.api.secret = GNOUI2EHGFGLZMCPQKOELJEFVBKKFCGP
sms.api.uri = https://api.coolsms.co.kr